name: articles_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  image_picker: ^1.0.7
  file_picker: ^6.2.0
  flutter_svg: ^2.0.10+1
  toggle_switch: ^2.1.0
  floating_draggable_widget: ^2.1.5
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.10
  cloud_firestore: ^4.15.9
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


# The following section is specific to Flutter packages.
flutter:

  
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  

  
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
